spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:6543/postgres?user=postgres.${DB_LINK}&password=${DB_PASSWORD}&prepareThreshold=0
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

cors.allowed-origins=http://localhost:4200,http://192.168.1.105:4200,https://oticasite.vercel.app
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
logging.level.org.hibernate.orm.boot=TRACE
logging.level.org.hibernate.mapping=TRACE
logging.level.org.hibernate.metamodel=TRACE
cloudinary.cloud-name=${API_MIDIA_NAME}
cloudinary.api-key=${API_MIDIA_KEY}
cloudinary.api-secret=${API_MIDIA_SECRET}
mercadopago.webhook-secret=${MP_WEBHOOK_SECRET}
mercadopago.access-token=${MP_ACCESS_TOKEN}

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
spring.jpa.hibernate.ddl-auto=update

server.tomcat.max-swallow-size=100MB
server.tomcat.max-http-form-post-size=100MB
