spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:5432/postgres?user=postgres.${DB_LINK}&password=${DB_PASSWORD}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

#spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
logging.level.org.hibernate.orm.boot=TRACE
logging.level.org.hibernate.mapping=TRACE
logging.level.org.hibernate.metamodel=TRACE
cloudinary.cloud-name=${API_MIDIA_NAME}
cloudinary.api-key=${API_MIDIA_KEY}
cloudinary.api-secret=${API_MIDIA_SECRET}
# 1. Configuração do Multipart do Spring (Aumentando bem o limite)
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
spring.jpa.hibernate.ddl-auto=update
# 2. Configuração do Servidor Tomcat Incorporado (Evita que o servidor recuse o payload bruto)
server.tomcat.max-swallow-size=100MB
server.tomcat.max-http-form-post-size=100MB
